### ISSUE TITLE
VAT calculation from EU to other countries?

### ISSUE THREAD

**Issue by DigitalLeaves** [valeriansaliou/node-sales-tax#15]
Just set up a new issue in case it's better for you (sorry about the inconvenience!). 

I need to calculate whether my SaaS should or not add VAT to the invoice for my customers (who are individual, natural persons without VAT number from inside and outside the EU). I'm in Estonia, EU. That means that I essentially need to add VAT to customers in the EU and don't add VAT to customers outside the EU.

However, the calculations from this library seem to not realize that I'm in Estonia, or I'm missing something when calling the library.

This is my code:

```
var SalesTax = require("sales-tax")

SalesTax.setTaxOriginCountry("EE", false)

var countries = [
    {"name": "Afghanistan", "code": "AF"},
    {"name": "land Islands", "code": "AX"},
    {"name": "Albania", "code": "AL"},
    ...
    {"name": "Zambia", "code": "ZM"},
    {"name": "Zimbabwe", "code": "ZW"}
]

countries.forEach(c => {
    SalesTax.getSalesTax(c.code, "EE").then((tax) => {
        console.log("VAT must be applied to a customer from " + c.name + "? "+JSON.stringify(tax))
    })
})
```

So what I would expect is to have a rate of 0.20 (20%) for all customers in EU (as my services require human intervention, so they don't fall in the category of MOSS or telecommunications downloads act), and 0% outside of EU (as I'm in Estonia, I can't charge any VAT or any extra tax to customers outside the EU).

So I would expect something like this:

```
...
VAT must be applied to a customer from Spain? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Suriname? {"type":"vat","rate":0.0,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Sweden? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Switzerland? {"type":"vat","rate":0.0,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
...
```

a Spanish o Swedish customer is in Europe: I charge 20% VAT
a customer from Suriname is outside EU: I don't charge VAT
a customer from Sweden is considered to be outside EU for VAT: I don't charge VAT
Instead, I get something like this:

```
VAT must be applied to a customer from Spain? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Suriname? {"type":"vat","rate":0.1,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Sweden? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Switzerland? {"type":"vat","rate":0.077,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
```

I kind of could use the "area" indicative, as it seems all EU countries have the "area" set to regional, but I need to trust this is valid and know why the VAT rate is not properly returned. Probably I'm doing something wrong.

Any help or insight greatly appreciated. Thanks!!!

**Comment by DigitalLeaves** [comment]
In fact, I realized that I cannot use the area code for that. One example: 
Monaco is considered to be part of France for VAT purposes. However, it shows as "worldwide", as if it was outside EU.

```
VAT must be applied to a customer from France? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Monaco? {"type":"none","rate":0,"area":"worldwide","exchange":"consumer","charge":{"direct":false,"reverse":false}}
```

**Comment by valeriansaliou** [comment]
Hello!

The library returns by default the tax number for non-EU countries. Though, it also returns `area`, which if it is `national` or `regional` you'd keep the VAT %, otherwise set it to zero. It still returns VAT rates for international countries, as if you have a nexus in some countries (eg. US states), you'd still owe some VAT there for US customers.

In your case, I'd just null out the VAT value if area is `wordwide`, and that will do it.

Regarding Monaco, thanks a ton. Adding it to the list of EU "countries" + adding the VAT rate.

If there are other country "exceptions" like Monaco, I'd be glad to hear about it so that I can update the library :)

**Comment by valeriansaliou** [comment]
Pushed in #a827eefca242c80e260c4216681c6c95260b0776
