### ISSUE TITLE
City sales tax?

### ISSUE THREAD

**Issue by jdimmerman** [valeriansaliou/node-sales-tax#17]
Hey - This is more of a question than an issue. I'm sorry if this is an inappropriate forum. I know that in the US, there are city/locale sales taxes and other sales taxes required for specific postal addresses in addition to state sales tax. Are those support in some way by this library?

Thanks!
Jason

**Comment by valeriansaliou** [comment]
Hello,

This is not supported. This tax model is too specific and too rare IMHO. This library was built for online services sales, in which case I’ve never seen a city tax being applied.

**Comment by jdimmerman** [comment]
Thanks @valeriansaliou. I'm certainly not well versed in what is required but am seeing indications that city level taxes are now required in some jurisdictions for SaaS providers. Example: https://www.krdcpas.com/does-chicagos-tax-on-cloud-computing-pertain-to-you/

I'm hoping that I'm misreading this or wrong though.

**Comment by valeriansaliou** [comment]
Yes. Indeed this library was designed for the SaaS world. Though if you’d like to contribute and add an (optional) city tax feature, I’m open to PRs :)

**Comment by jdimmerman** [comment]
Thanks @valeriansaliou. Understood! Thanks for implementing and publishing this package.
