### ISSUE TITLE
I get incorrect responses back, any idea why?

### ISSUE THREAD

**Issue by stijnvanlieshout** [valeriansaliou/node-sales-tax#18]
Hi there, 
I just installed this package and am sure it will help me a lot in handling VAT. 

The problem I'm encountering is that the responses I get back are incorrect. I do exactly as instructed in the docs. Any idea why I'm getting invalid responses back?

Example from the documentation:

```
SalesTax.setTaxOriginCountry("FR")
SalesTax.getSalesTax("FR", null, "FR50833085806")
  .then((tax) => {
       console.log("tax", tax)
  });`
```

Expected response:
```
   {
        type     : "vat",
        rate     : 20.00,
        area     : "national",
        exchange : "business",

        charge   : {
          direct  : true,
          reverse : false
        }
   }
```
Actual response:
![Screenshot 2020-01-07 at 10 42 36](https://user-images.githubusercontent.com/8589586/71889626-75a78b00-313a-11ea-9c4a-7ecf806bb573.png)

**Comment by valeriansaliou** [comment]
Hello!

Can you try it this way:

```js
SalesTax.setTaxOriginCountry("FR", false);

SalesTax.toggleEnabledTaxNumberValidation(false);
SalesTax.toggleEnabledTaxNumberFraudCheck(false);
```

And then:

```js
return SalesTax.getSalesTax("FR", null, "FRXXXXXX");
```

**Comment by stijnvanlieshout** [comment]
I just tried that but the result remains the same:

![Screenshot 2020-01-07 at 11 32 46](https://user-images.githubusercontent.com/8589586/71892673-755ebe00-3141-11ea-891d-e4ee2a74f636.png)

I get this result regardless of the origin country/sales tax country arguments I feed in. So the result is the same for:

```
SalesTax.setTaxOriginCountry("IT", false);
SalesTax.getSalesTax("NL", null, null)

```

**Comment by valeriansaliou** [comment]
I just tested, and I'm not encountering any issue:

```js
var SalesTax = require("sales-tax");

console.log("Testing Sales Tax...");

SalesTax.setTaxOriginCountry("FR");

SalesTax.getSalesTax("FR", null, "FR50833085806")
  .then((tax) => {
    console.log("Done testing Sales Tax:", tax);
  });
```

Result in console:

```

```

**Comment by stijnvanlieshout** [comment]
I just also made a create react app project, installed it there, and then it also works just fine for me. 
Seems like something is going wrong in the build process for the other app... I will have a look and see if can solve it. Thanks for the help!

**Comment by stijnvanlieshout** [comment]
FYI: I've created an issue in the fusebox repo (the bundler that I use): https://github.com/fuse-box/fuse-box/issues/1745
