### ISSUE TITLE
international  vs. worldwide?

### ISSUE THREAD

**Issue by JonasGruenwald** [valeriansaliou/node-sales-tax#19]
Hi, I was wondering about this part of the readme:

> To make things easier for you, sales-tax returns an `area` parameter in the SalesTax.getSalesTax, that is either `international`, `regional` or `national` (this depends on your configured origin country). For regional and national areas, you can trust the returned rate. However, you may need to override all international area rates and void them all to zero; for instance if you charge from France to the United States, and you know that you do not owe sales tax in the US as you do not run a nexus company in the US.

As far as I can tell, the area parameter returned for VAT calculation from EU to other countries is `worldwide` and not `international` as described above, is this an error in the readme or am I doing something wrong?

**Comment by valeriansaliou** [comment]
Thanks, this was indeed a naming mistake in the README, probably for historic reasons. It's been normalized to `worldwide` everywhere in 20f1978e5151847787ef5f9f209906f52a9fcb48
