### ISSUE TITLE
Withdraw the UK from EU country list on 31st Dec 2020 ~ 1st Jan 2021

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/node-sales-tax#26]
Due to Brexit, a transition period is in place; no VAT-related changes are to be implemented in 2020, though on 31st December 2020 the UK (may) be pulled from the EU VAT country list.

File: https://github.com/valeriansaliou/node-sales-tax/blob/master/res/region_countries.json
Reference: https://ec.europa.eu/taxation_customs/uk_withdrawal_en

**Comment by M0rph3v5** [comment]
hey, I think it's time they need to be removed right?

**Comment by valeriansaliou** [comment]
@M0rph3v5 I guess so, I've sent an email to my accountant to confirm the legal basis of that, and either remove it now or schedule deletion in the library once I have a response.

If you have an earlier response from an accountant, you can forward it there :)

**Comment by valeriansaliou** [comment]
ref 40643663075861adce584efa92c1485520691aa2

**Comment by valeriansaliou** [comment]
Published as of `sales-tax@2.2.6`
