### ISSUE TITLE
Check a UK VAT number API

### ISSUE THREAD

**Issue by Capaman** [valeriansaliou/node-sales-tax#40]
Thanks for this package!

Could you include the UK VAT number API:

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/

... in the VAT validation?!

Many thanks!

**Comment by valeriansaliou** [comment]
Sure! I have no direct use of this, so I'm accepting PRs :)

**Comment by Capaman** [comment]
... why 'no direct use' if I may ask?! :-)

**Comment by valeriansaliou** [comment]
We're not using the VAT number validation features over at Crisp. I've got some free time ahead though, so I will do it :)

**Comment by valeriansaliou** [comment]
All good! You may update to `sales-tax` `v2.3.0`!
