### ISSUE TITLE
Australia

### ISSUE THREAD

**Issue by aintHuman** [valeriansaliou/node-sales-tax#43]
My business is from Australia, So broadly speaking, we have GST, which is 10%. 

But export sales (ie sales from Australia to some other domicile) is GST free.

Unless I have misunderstood the usage of your software, this is not reflected in the output from your code.

I am expecting to set my business tax origin to Australia (AU).

Then:
+ sales tax (GST) for a customer from Australia should yield 10% (CASE 1 Below)
+ sales tax for a customer OUTSIDE of Australia should yield 0% (CASE 2 Below)

My expectations come about after reading the README file, specifically, with respect to the `getSalestax(...)` method, where you have stated:

> this method is origin-aware. It means it return values relative to your configured tax origin country

So below is a typical query that I would expect to make:

```
// SET MY ORIGIN TO AUSTRALIA
SalesTax.setTaxOriginCountry('AU')

// [CASE 1] Domestic Customer -- THIS RESULT IS CORRECT
SalesTax.getSalesTax("AU").then(console.log);

{
  type: 'gst',
  rate: 0.1,
  area: 'national',
  exchange: 'consumer',
  charge: { direct: true, reverse: false },
  details: [ { type: 'gst', rate: 0.1 } ]
}

// [CASE 2] International Customer (eg USA) -- THIS RESULT IS NOT CORRECT (According to my Understanding)
SalesTax.getSalesTax("US","CA").then(console.log);

{
  type: 'vat',
  rate: 0.0825, // <------- WRONG
  area: 'worldwide',
  exchange: 'consumer',
  charge: { direct: true, reverse: false },
  details: [ { type: 'vat', rate: 0.0825 } ]
}

```

**Comment by valeriansaliou** [comment]
Hello,

In your second query, you’re fetching the sales tax value for an US state. Thus, it returns the sales tax for this US state (federal + state if any). Even if your origin is set to Australia.

Note that you should probably apply a post processing filter on the top of the library based on your country export laws regarding how sales taxes should be calculated for international sales.

To be clear, that origin setter method is only useful for EU VATMOSS calculation as this helps calculate B2B and B2C VAT with EU VAT number validation. International VAT rules outside the EU VATMOSS scheme are unclear to me and differ a lot between countries so you should apply your own filters in those cases.

Note that though, local VAT rates are still correct, ie. Australia to Australia. International rules vary depending on your country though.

**Comment by aintHuman** [comment]
Thanks, I found the following which I can adapt to do the job:

 https://github.com/valeriansaliou/node-sales-tax/issues/5
