### ISSUE TITLE
Tax from EU to non-EU

### ISSUE THREAD

**Issue by nuthinking** [valeriansaliou/node-sales-tax#5]
I have a business in the UK that would like to sell a digital subscription globally. Assuming my business is registered for MOSS, to pay all EU VAT to UK. What should I tax non-EU customers?
Following our conversation on Twitter, I should basically **NOT** charge Taxes (like VAT) to customers outside the EU, regardless if business or consumer (btw this is in contrast with [some things](https://www.ukbusinessforums.co.uk/threads/digital-service-vat.381093/) I read online, where countries like Japan, New Zeland etc.. want to tax these goods).
If in my case no tax is due to non-EU customer, how do I use the library to get that result?

Either value I pass to setTaxOriginCountry as useRegionalTax for origin **UK** for a customer in **California**, I always get **8.25% VAT**:

```javascript
    const SalesTax = require('sales-tax');
    SalesTax.setTaxOriginCountry("UK", false);
    SalesTax.getSalesTax("US", "CA")
      .then((tax) => {
        console.log(tax);
        /* tax ===
          {
            type: 'vat',
            rate: 0.0825,
            area: 'worldwide',
            exchange: 'consumer',
            charge: { direct: true, reverse: false }
          }
         */
      });
```
I would assume I should pass **true** btw, since hopefully there will be enough turnover and hopefully MOSS will be needed.

**Comment by valeriansaliou** [comment]
Okay, I confirm I'm actually double filtering EU countries in Crisp upon VAT calculation using the library. This way I override the returned VAT to zero if the country is non-EU. Adding a direct way to do this in sales-tax today.

**Comment by valeriansaliou** [comment]
Okay, my bad for what I told you. It's been 1 year I have not touched this code, so I felt a bit off of it.

Here's what we have in Crisp when we call the library:

```javascript
return Promise.resolve()
  .then(() => {
    // Acquire sales tax for customer
    return SalesTax.getSalesTax(
      country, null, tax_identifier
    );
  })
  .then((sales_tax) => {
    // Acquire base tax parameters
    let _tax_rate    = (sales_tax.rate || 0.0);
    let _tax_reverse = ((sales_tax.charge || {}).reverse || false);

    // Assign local tax specifities
    switch (sales_tax.area) {
      case "national": {
        // Charge taxes only for national area
        return Promise.resolve({
          rate    : _tax_rate,
          area    : "national",
          rule    : null,
          reverse : _tax_reverse
        });
      }

      case "regional": {
        // Do not charge tax for regional area (apply EU tax code)
        // Notice: in some cases taxes may still be charged
        return Promise.resolve({
          rate    : _tax_rate,
          area    : "regional",
          rule    : ((_tax_rate === 0.0) ? "EU-CE-2006-112" : null),
          reverse : _tax_reverse
        });
      }

      default: {
        // Do not charge tax for international area \
        //   (apply foreign tax code)
        return Promise.resolve({
          rate    : 0.0,
          area    : "international",
          rule    : "FR-CGI-259",
          reverse : true
        });
      }
    }
  });
```

As you see, we use the returned region to override returned VAT number (`national` if UK for you, `regional` if EU but not UK, or wordwide for the rest). Thing is, in some cases it's correct to return the VAT rate, eg. if you bill from the UK but have a nexus in the US, you still need to collect US VAT for the US state your nexus is in (very complicated international VAT rules).

So, the correct way to handle this is to use the returned `area` to alter returned VAT at your convenience, to handle special international rules for which the library cannot guess about, that depends on your legal structure & others.

**Comment by valeriansaliou** [comment]
Added a README notice to make things clear for library users in your case: https://github.com/valeriansaliou/node-sales-tax#i-bill-from-the-eu-but-sales-tax-is-still-being-returned-for-non-eu-countries

Thanks!

**Comment by nuthinking** [comment]
Gotcha! The problem is that I always get as area "worldwide" even if I set origin UK and sell in UK, regardless of the parameter passed in setTaxOriginCountry. And it returns tax of 0%.

```
const SalesTax = require('sales-tax');
SalesTax.setTaxOriginCountry("UK");
SalesTax.getSalesTax("UK")
  .then((tax) => {
    console.log(tax);
    /* tax ===
      { type: 'none',
        rate: 0,
        area: 'worldwide',
        exchange: 'consumer',
        charge: { direct: false, reverse: false } }
     */
  });
```

**Comment by valeriansaliou** [comment]
Mhh, it's not possible to be a bug in that case, unit tests all pass. Which version of NodeJS do you run?

**Comment by valeriansaliou** [comment]
I'd avise initializing once sales-tax as such:

```javascript

    // Configure tax library
    SalesTax.setTaxOriginCountry(
      "UK", false
    );

    SalesTax.toggleEnabledTaxNumberValidation(false);
    SalesTax.toggleEnabledTaxNumberFraudCheck(false);
```

Fraud check hits against the EU's VAT number verification API, that can quite unstable, so you may want to disable this.

**Comment by valeriansaliou** [comment]
Ah nap, sorry about that.

GB is not listed in the EU in my list, I actually prepared the library for brexit; if it's still active in the EU VAT, let me know and I'll add it back in the list.

**Comment by nuthinking** [comment]
It is still in the EU until March 2019. I also got the feeling they will keep the MOSS working for some time afterwards.

**Comment by valeriansaliou** [comment]
Okay, cool. Published `v2.0.7`, can you test w/ this one?

**Comment by nuthinking** [comment]
Looks to be working now, thanks!
To be honest, since I think I will have to detect if the customer is in Europe before calling the function anyway (Stripe cards don't return the country code but the country name), I could forget about the override you suggested above and not using the library for non-EU.
Thanks again!

**Comment by DigitalLeaves** [comment]
Hello, I'm having this exact same problem. I need to calculate whether my SaaS should or not add VAT to the invoice for my customers (who are individuals without VAT number) from inside and outside the EU. I'm in Estonia, EU. That means that I essentially need to add VAT to customers in the EU and not add VAT in customers outside the EU.

However, the calculations from this library seem to not realize that I'm in Estonia, or I'm missing something when calling the library.

This is my code:

```
var SalesTax = require("sales-tax")

SalesTax.setTaxOriginCountry("EE", false)

var countries = [
    {"name": "Afghanistan", "code": "AF"},
    {"name": "land Islands", "code": "AX"},
    {"name": "Albania", "code": "AL"},
    ...
    {"name": "Zambia", "code": "ZM"},
    {"name": "Zimbabwe", "code": "ZW"}
]

countries.forEach(c => {
    SalesTax.getSalesTax(c.code, "EE").then((tax) => {
        console.log("VAT must be applied to a customer from " + c.name + "? "+JSON.stringify(tax))
    })
})
```

So what I would expect is to have a rate of 0.20 (20%) for all customers in EU (as my services require human intervention, so they don't fall in the category of MOSS or telecommunications downloads act), and 0% outside of EU (as I'm in Estonia, I can't charge any VAT or any extra tax to customers outside the EU).

So I would expect something like this:
```
...
VAT must be applied to a customer from Spain? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Suriname? {"type":"vat","rate":0.0,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Sweden? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Switzerland? {"type":"vat","rate":0.0,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
...
```
- a Spanish o Swedish customer is in Europe: I charge 20% VAT
- a customer from Suriname is outside EU: I don't charge VAT
- a customer from Sweden is considered to be outside EU for VAT: I don't charge VAT

Instead, I get something like this:
```
VAT must be applied to a customer from Spain? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Suriname? {"type":"vat","rate":0.1,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Sweden? {"type":"vat","rate":0.2,"area":"regional","exchange":"consumer","charge":{"direct":true,"reverse":false}}
VAT must be applied to a customer from Switzerland? {"type":"vat","rate":0.077,"area":"worldwide","exchange":"consumer","charge":{"direct":true,"reverse":false}}
```

I kind of could use the "area" indicative, as it seems all EU countries have the "area" set to regional, but I need to trust this is valid and know why the VAT rate is not properly returned. Probably I'm doing something wrong.

Any help or  insight greatly appreciated. Thanks!!!
