### ISSUE TITLE
TAX changes Ghana, Lithuania, Moldova, Spain

### ISSUE THREAD

**Issue by black-hawk85** [valeriansaliou/node-sales-tax#57]
Hi,

got a notification mail from Apple yesterday about TAX changes.
Just wanted to make sure you are aware about it :-)

![2023-06-01 Apple](https://github.com/valeriansaliou/node-sales-tax/assets/24221330/eef74ec3-edd8-4c52-bb5e-451c8ffc0a3b)

**Comment by valeriansaliou** [comment]
I issued `v2.11.0`, w/ the fix for Ghana. Other VAT rate changes are specific to an industry eg. Spain's DST, therefore should not be included in this library. Thank you again!
